# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(choices=[('COP', 'Car Operating Panel'), ('HAPS', 'HAPS battery'), ('SHC', 'Serial Hall Calls')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tech_name', models.CharField(max_length=50)),
                ('job_num', models.CharField(max_length=10)),
                ('ship_date', models.DateTimeField(verbose_name='Shipping Date')),
                ('status', models.CharField(choices=[('Beginning', 'Beginning'), ('Program', 'Program'), ('Logic', 'Logic'), ('Ending', 'Ending'), ('Complete', 'Complete'), ('Stopped', 'Stopped')], max_length=50)),
                ('prev_stage', models.CharField(choices=[('Beginning', 'Beginning'), ('Program', 'Program'), ('Logic', 'Logic'), ('Ending', 'Ending'), ('Complete', 'Complete')], max_length=50)),
                ('current_index', models.IntegerField(max_length=2)),
                ('job_type', models.CharField(choices=[('2000', 'M2000'), ('4000', 'M4000'), ('ELEM', 'Element')], max_length=50)),
                ('stage_len', models.IntegerField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'My Jobs',
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
                ('stop_start_time', models.DateTimeField(verbose_name='"Stop" start date')),
                ('stop_end_time', models.DateTimeField(verbose_name='"Stop" finish date')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodfloor.Info')),
            ],
            options={
                'verbose_name_plural': 'Stops per Job',
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_1', models.DateTimeField(verbose_name='"Inicio de Test" start date')),
                ('end_time_1', models.DateTimeField(verbose_name='"Inicio de Test" finish date')),
                ('start_time_2', models.DateTimeField(verbose_name='"Programacion" start date')),
                ('end_time_2', models.DateTimeField(verbose_name='"Programacion" finish date')),
                ('start_time_3', models.DateTimeField(verbose_name='"Pruebas logicas" start date')),
                ('end_time_3', models.DateTimeField(verbose_name='"Pruebas logicas" finish date')),
                ('start_time_4', models.DateTimeField(verbose_name='"Fin de Test" start date')),
                ('end_time_4', models.DateTimeField(verbose_name='"Fin de Test" finish date')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodfloor.Info')),
            ],
        ),
        migrations.AddField(
            model_name='features',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodfloor.Info'),
        ),
        migrations.CreateModel(
            name='MyJob',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'All Jobs',
            },
            bases=('prodfloor.info',),
        ),
        migrations.CreateModel(
            name='StopsInfo',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'All Stops',
            },
            bases=('prodfloor.info',),
        ),
    ]
