# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0002_auto_20170116_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='label',
            field=models.CharField(default='-', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stops',
            name='reason',
            field=models.CharField(choices=[('Job reassignment', 'Job reassignment'), ('Reason 1', 'Reason 1'), ('Reason 2', 'Reason 2'), ('Reason 3', 'Reason 3'), ('Reason 4', 'Reason 4'), ('Reason 5', 'Reason 5'), ('Reason 6', 'Reason 6')], max_length=200),
        ),
    ]
