# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0003_auto_20170119_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='station',
            field=models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8'), ('9', 'S9'), ('10', 'S10'), ('11', 'S11'), ('12', 'S12'), ('13', 'ELEM1'), ('14', 'ELEM2')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stops',
            name='reason',
            field=models.CharField(choices=[('Job reassignment', 'Job reassignment'), ('Shift ended', 'Shift ended'), ('Reason 1', 'Reason 1'), ('Reason 2', 'Reason 2'), ('Reason 3', 'Reason 3'), ('Reason 4', 'Reason 4'), ('Reason 5', 'Reason 5'), ('Reason 6', 'Reason 6')], max_length=200),
        ),
    ]
