# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0004_auto_20170127_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='po',
            field=models.CharField(default=21, max_length=7),
            preserve_default=False,
        ),
    ]
