# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0005_stops_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='po',
            field=models.CharField(default=3375201, max_length=7),
            preserve_default=False,
        ),
    ]
