# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0006_times_po'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_one_cause', models.CharField(choices=[('Job reassignment', 'Job reassignment'), ('Shift ended', 'Shift ended'), ('Reason 1', 'Reason 1'), ('Reason 2', 'Reason 2'), ('Reason 3', 'Reason 3'), ('Reason 4', 'Reason 4'), ('Reason 5', 'Reason 5'), ('Reason 6', 'Reason 6')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tier2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_two_cause', models.CharField(max_length=200)),
                ('tier_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodfloor.Tier1')),
            ],
        ),
        migrations.CreateModel(
            name='Tier3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_three_cause', models.CharField(max_length=200)),
                ('tier_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodfloor.Tier2')),
            ],
        ),
        migrations.AlterField(
            model_name='features',
            name='features',
            field=models.CharField(choices=[('COP', 'Car Operating Panel'), ('SHC', 'Serial Hall Calls'), ('HAPS', 'HAPS battery'), ('OVL', 'Overlay'), ('GROUP', 'Group'), ('mView', 'mView'), ('iMon', 'iMonitor'), ('DCC', 'Door Control in Cartop'), ('CPI', 'CPI Board Included')], max_length=200),
        ),
    ]
