# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0007_auto_20170207_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='reason',
            field=models.CharField(choices=[('Job reassignment', 'Job reassignment'), ('Shift ended', 'Shift ended'), ('Error Funcional', 'Error Funcional'), ('Tarjetas T', 'Tarjetas T'), ('Material Faltante', 'Custom Software Faltante'), ('Junta de supervisor', 'Junta de supervisor'), ('Tecnico no asignado', 'Tecnico no asignado'), ('Personal', 'Personal'), ('Ingenieria', 'Ingenieria'), ('Falla en equipo de computo', 'Falla en equipo de computo'), ('Entrenamiento', 'Entrenamiento')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tier1',
            name='tier_one_cause',
            field=models.CharField(choices=[('Job reassignment', 'Job reassignment'), ('Shift ended', 'Shift ended'), ('Error Funcional', 'Error Funcional'), ('Tarjetas T', 'Tarjetas T'), ('Material Faltante', 'Custom Software Faltante'), ('Junta de supervisor', 'Junta de supervisor'), ('Tecnico no asignado', 'Tecnico no asignado'), ('Personal', 'Personal'), ('Ingenieria', 'Ingenieria'), ('Falla en equipo de computo', 'Falla en equipo de computo'), ('Entrenamiento', 'Entrenamiento')], max_length=200),
        ),
    ]
