# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0008_auto_20170210_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='extra_cause_1',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='extra_cause_2',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stops',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
