# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodfloor', '0009_auto_20170214_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier2',
            name='tier_one',
        ),
        migrations.RemoveField(
            model_name='tier3',
            name='tier_two',
        ),
        migrations.RemoveField(
            model_name='times',
            name='po',
        ),
        migrations.DeleteModel(
            name='Tier1',
        ),
        migrations.DeleteModel(
            name='Tier2',
        ),
        migrations.DeleteModel(
            name='Tier3',
        ),
    ]
