from django.utils.translation import ugettext_lazy as _

dict_m2000_new = {
    'Beginning': [['Documentacion Inicial', [None,], [None,]],
                  ['Traer Material Externo Del Controlador', [None,], [None,]],
                  ['Inspeccion Visual', [None,], [None,]],
                  ['Preparacion de Labview', [None,], [None,]],
                  ['Conectar Lineas Principales de Poder', [None,], [None,]],
                  ['Chequeo preliminar de voltajes iniciales', [None,], [None,]]],
    'Program': [['Programacion de Flasheo', [None,], [None,]],
                ['Conexion de arneces simulador del carro y arneces cartop', ['CPI'], [1]],
                ['Programacion del Firmware(Chip)', [None,], [None,]],
                ['Conexion de arneces del simulador', ['CPI'], [0]],
                ['Programacion y Ajuste del Starter', [None,], [None,]],
                ['Programacion de parametros F1', [None,], [None,]],
                ['Programacion de Fecha y Hora', [None], [None]],
                ['Programacion de F4(Labels)', [None,], [None,]]],
    'Logic': [['Board power test SAFL & SAFS', [None,], [None,]],
              ['Motor Starter Test', [None,], [None,]],
              ['Valve control and limits', [None,], [None,]],
              ['Safety and inspection(Pag 8)', [None,], [None,]],
              ['Door locks and hoistway access', [None,], [None,]],
              ['Landing system', [None,], [None,]],
              ['Door Interface (Pag CT1, CT2)', ['DCC'], [1]],
              ['COP parte 1 (Pag CPI)', ['DCC'], [1]],
              ['Door Interface (Pag 11, 11X)', ['DCC'], [0]],
              ['COP parte 1 (Pag 12)', ['DCC'], [0]],
              ['Fire Service Phase I (Pag 13)', [None,], [None,]],
              ['Fire Service Phase II (Pag 12)', ['CPI'], [0]],
              ['Movement Indication (Pag 14)', ['CPI'], [0]],
              ['Fire Service Phase II (Pag COP)', ['CPI'], [1]],
              ['Movement Indication (Pag COP)', ['CPI'], [1]],
              ['Car Calls (Pag COP)', ['CPI'], [1]],
              ['Calls (Pag 16)', ['CPI'], [0]],
              ['Serial Hall Calls (Pag SH)', ['SHC'], [1]],
              ['Pruebas de entradas y salidas (Pag 15, 17, etc.)', [None,], [None,]],
              ['Pruebas con OVL del Job o Switches para OVL', ['OVL',], [1,]],
              ['Calibracion EMCO Board', ['EMCO','CPI'], [1, 1]],
              ['Pruebas de entradas y salidas CARTOP (Pag CT1, CT2, etc.)', ['CPI'], [1]],
              ['Pruebas con MGROUP del Job o MGROUP de Prueba', ['LOC'], [1]],
              ['Pruebas de Compliance (Documento 42-CR-0001)', ['CTL2', 'CAN'], [1, 1]],
              ['Pruebas de Factory Test Report 2010', ['CTL2','TSSA'], [1, 1]],
              ['Flasheo de Puerto CHP y/o MPU', ['mView','iMon'], [1, 1]],
              ['Flasheo de Puerto CHP y/o MPU', ['mView','iMon'], [0, 1]],
              ['Flasheo de Puerto CHP y/o MPU', ['mView','iMon'], [1, 0]],
              ['Configuracion de PC, Imagen y Softwares', ['PC','mView','iMon'], [1, 1, 1]],
              ['Configuracion de PC, Imagen y Softwares', ['PC','mView','iMon'], [1, 0, 1]],
              ['Configuracion de PC, Imagen y Softwares', ['PC','mView','iMon'], [1, 1, 0]],
              ['Prueba de Monitoring', ['mView','iMon'], [1, 1]],
              ['Prueba de Monitoring', ['mView','iMon'], [0, 1]],
              ['Prueba de Monitoring', ['mView','iMon'], [1, 0]], ],
    'Ending': [['Modificacion Parametros F1 Version Cliente', [None,], [None,]],
               ['Inspeccion Final', [None,], [None,]],
               ['Passcode', [None,], [None,]],
               ['Papeleria Final', [None,], [None,]],
               ['Respaldo Electronico de la papeleria', [None,], [None,]],
               ['Desconnecion de Arneces', [None,], [None,]],],
    'Complete': [['Carro a estacion final', [None], [None]],
                 ['Fin de pruebas', [None,], [None,]]],
    'Stopped': ['Detenido'],
    'Reassigned': ['Reasignado'],}
dict_m4000_new = {
    'Beginning': [['Documentacion Inicial', [None], [None]],
                  ['Traer Material Externo Del Controlador', [None,], [None,]],
                  ['Inspeccion Visual', [None], [None]],
                  ['Preparacion de Labview', [None], [None]],
                  ['Conectar Lineas Principales de Poder', [None,], [None,]],
                  ['Chequeo preliminar de voltajes iniciales', [None], [None]], ],
    'Program': [['Programacion de Flasheo', [None], [None]],
                ['Conexion de arneces simulador del carro y arneces cartop', ['CPI'], [1]],  # if cartop
                ['Programacion del Firmware(Chip)', [None], [None]],
                ['Conexion de arneces del simulador', ['CPI'], [0]],  # if !cartop
                ['Programacion de parametros F1', [None], [None]],
                ['Programacion de Parametros F7\n Version Test', [None], [None]],
                ['Programacion de Parametros F5\n Version Test', [None], [None]],
                ['Programacion de Fecha y Hora', [None], [None]],
                ['Programacion de R6 Regen Unit', ['R6'], [1]],
                ['Programacion de F4(Labels)', [None], [None]],
                ['MBRAKE Module\nCalibracion Inicial', ['MBRAKE'], [1]],
                ['Calibracion Brake Coil Discreto Final', ['MBRAKE', 'BCV'], [0, 1]],
                ['Calibracion Brake Coil Discreto Preliminar', ['MBRAKE', 'BCV'], [0, 0]],
                ['Calibracion F6 Floor Learning', [None], [None]],
                ['F7 Terminal Limits', [None], [None]], ],
    'Logic': [['Board power test SAFL & SAFS', [None], [None]],
              ['Drive Interface', [None], [None]],
              ['Emergency Brake', [None], [None]],
              ['Safety and inspection(Pag 8)', [None], [None]],
              ['Door locks and hoistway access', [None], [None]],
              ['Landing System', [None], [None]],
              ['Door Interface (Pag CT1, CT2)', ['DCC'], [1]],  # if DCC
              ['COP parte 1 (Pag CPI)', ['DCC'], [1]],  # if DCC
              ['Door Interface (Pag 11, 11X)', ['DCC'], [0]],  # if !DCC
              ['COP parte 1 (Pag 12)', ['DCC'], [0]],  # if !DCC
              ['Fire Service Phase I (Pag 13)', [None], [None]],
              ['Fire Service Phase II (Pag 12)', ['CPI'], [0]],  # if !CPI
              ['Movement Indication (Pag 14)', ['CPI'], [0]],  # if !CPI
              ['Fire Service Phase II (Pag CPI)', ['CPI'], [1]],  # if CPI
              ['Movement Indication (Pag CPI)', ['CPI'], [1]],  # if CPI
              ['Car Calls (Pag CPI)', ['CPI'], [1]],  # if CPI
              ['Calls (Pag 16)', ['CPI'], [0]],
              ['Serial Hall Calls (Pag SH)', ['SHC'], [1]],  # if serial hall calls
              ['Pruebas de entradas y salidas (Pag 15, 17, etc.)', [None], [None]],
              ['Pruebas con OVL del Job o Switches para OVL', ['OVL',], [1,]],
              ['Calibracion EMCO Board', ['EMCO','CPI'], [1, 1]],
              ['Pruebas de entradas y salidas CARTOP (Pag CT1, CT2, etc.)', ['CPI'], [1]],
              ['Pruebas con MGROUP del Job o MGROUP de Prueba', ['LOC'], [1]],
              ['Pruebas de Compliance', ['CTL2'], [1]],
              ['Pruebas de Factory Test Report', ['CTL2','TSSA'], [1, 1]],
              ['Flasheo de Puerto CHP y/o MPU', ['mView','iMon'], [1, 1]],
              ['Flasheo de Puerto CHP y/o MPU', ['mView','iMon'], [0, 1]],
              ['Flasheo de Puerto CHP y/o MPU', ['mView','iMon'], [1, 0]],
              ['Configuracion de PC, Imagen y Softwares', ['PC','mView','iMon'], [1, 1, 1]],
              ['Configuracion de PC, Imagen y Softwares', ['PC','mView','iMon'], [1, 0, 1]],
              ['Configuracion de PC, Imagen y Softwares', ['PC','mView','iMon'], [1, 1, 0]],
              ['Prueba de Monitoring', ['mView','iMon'], [1, 1]],
              ['Prueba de Monitoring', ['mView','iMon'], [0, 1]],
              ['Prueba de Monitoring', ['mView','iMon'], [1, 0]],
              ['Additional Manual Test\n(Overspeeds and Limits)', [None], [None]],
              ['Programacion del PLC', ['MRL'], [1]],
              ['Monitoreo de video con Panel', ['MRL'], [1]],
              ['Monitoreo de Bateria', ['MRL'], [1]],
              ['Brake Release del MRL', ['MRL'], [1]],
              ['MBRAKE\nCalibracion Final', ['MBRAKE'], [1]],
              ['Calibracion Brake Coil Discreto Final', ['MBRAKE','BCV'], [0, 0]],
              ['Programacion de Parametros F7\n Version Cliente', [None], [None]],
              ['Programacion de Parametros F5\n Version Cliente', [None], [None]],
              ['Programacion de Parametros F1\n Version Cliente', [None], [None]], ],
    'Ending': [['Inspeccion Final', [None], [None]],
               ['Passcode', [None], [None]],
               ['Papeleria Final', [None], [None]],
               ['Respaldo Electronico de la papeleria', [None], [None]],
               ['Desconnecion de Arneces', [None], [None]], ],
    'Complete': [['Carro a estacion final', [None], [None]],
                 ['Fin de pruebas', [None], [None]], ],
    'Stopped': ['Detenido'],
    'Reassigned': ['Reasignado'],}
dict_elem_new = {
    'Beginning': [['Configuracion Inicial de PC', [None], [None]],
                  ['Conseguir Software(Update) y Parametros(XML)', [None], [None]],
                  ['Crear Carpeta del Job y Crear Archivos de Documentacion:\nStarter REC, Board Information', [None], [None]],
                  ['Escanear Codigos de Barras de Tarjetas y Dispositivos', [None], [None]],
                  ['Crear Documentacion de Visual Inspection List, Tech Report y Passcode', [None], [None]],
                  ['Inspeccionar Jumpers y Switches', [None], [None]],
                  ['Checar Voltajes', [None], [None]], ],
    'Program': [['Flashear HAPS', ['SHC'], [1]],  # If HAPS
                ['Cargar el Software(Update)', [None], [None]],
                ['Conectar Arneces', [None], [None]],
                ['Cargar Software en el LS-EDGE del Cliente', ['EDGE'], [1]],
                ['Cambiar parametro xml "Landing System Type" value="1" (Solo test)', ['EDGE'], [0]],
                ['Verificar Tolerancias de AC por Medio de LabView', [None], [None]],
                ['Cargar los Parametros(XML)', [None], [None]],
                ['Agregar y Modificar Datos de Test', [None], [None]],
                ['Prueba Automatizada de LabView', [None], [None]], ],
    'Ending': [['Respaldar Electronicamente el Reporte de Prueba Automatizada', [None], [None]],
               ['Hacer pruebas de tolerancias de voltajes MOD Door Operator', ['MOD'], [1]],
               ['Devolver Parametros Originales de Cliente', [None], [None]],
               ['Extraer los Parametros(CCF)', [None], [None]],
               ['Introducir el Passcode', [None], [None]],
               ['Poner el Controlador en Construction Mode', [None], [None]],
               ['Imprimir Papeleria Final', [None], [None]],
               ['Hacer Respaldo Electronico de Documentos al Servidor', [None], [None]],],
    'Logic': [['', [None], [None]], ],
    'Complete': [['Carro a Estacion Final', [None], [None]],['Fin de pruebas', [None], [None]], ],
    'Stopped': ['Detenido'],
    'Reassigned': ['Reasignado'],}
dict_elemt_new = {
    'Beginning': [['Configuracion Inicial de PC', [None], [None]],
                  ['Conseguir Software(Update) y Parametros(XML)', [None], [None]],
                  ['Crear Carpeta del Job y Crear Archivos de Documentacion:\nStarter REC, Board Information', [None], [None]],
                  ['Escanear Codigos de Barras de Tarjetas y Dispositivos', [None], [None]],
                  ['Crear Documentacion de Visual Inspection List, Tech Report y Passcode', [None], [None]],
                  ['Inspeccionar Jumpers y Switches', [None], [None]],
                  ['Checar Voltajes', [None], [None]], ],
    'Program': [['Cargar el Software(Update)', [None], [None]],
                ['Cargar los parametros(XML)', [None], [None]],
                ['Resetear parametros del drive(U5)', [None], [None]],
                ['Llenar parametros del drive(Version Test)', [None], [None]],
                ['Conectar Arneces, cables del motor y cables del encoder', [None], [None]],
                ['Cargar Software en el LS-EDGE del Cliente', [None], [None]],
                ['Ajustar la resistencia RB(3 veces el coil resistance de cliente)', [None], [None]],
                ['Ajustar los voltajes del freno del motor(Version Test)', [None], [None]],
                ['Verificar corrientes y velocidades de inspecion(DO Display)', [None], [None]],
                ['Calibracion Hoistway Learning', [None], [None]],
                ['Calibracion terminal switches', [None], [None]],
                ['Probar los "Speeds"(High, leveling y correction)', [None], [None]],
                ['Probar los "Overspeeds"(Inspection, leveling y contract)', [None], [None]],
                ['Probar el drive(Encoder loss, phase fault, DC bus voltage)', [None], [None]],
                ['Probar los terminal switches(UETS/DETS overspeed)', [None], [None]],
                ['Probar los terminal slowdoen(UNTS1/DNTS1 lower/upper overspeed)', [None], [None]],
                ['Probar los contactores(High, leveling y correction)', [None], [None]],
                ['Probar Señales logicas marcadas en print', [None], [None]], ],
    'Ending': [['Ajustar parametros de cliente del XML', [None], [None]],
               ['Ajustar los voltajes del freno del motor(Version Cliente), traer resistencia de carga', [None], [None]],
               ['Llenar parametros del drive(Version Cliente)', [None], [None]],
               ['Hacer pruebas de tolerancias de voltajes MOD Door Operator', ['MOD'], [1]],
               ['Extraer los parametros de la CPU(CCF)', [None], [None]],
               ['Introducir el Passcode(En caso de que aplique)', [None], [None]],
               ['Poner el Controlador en Construction Mode', [None], [None]],
               ['Imprimir Papeleria Final', [None], [None]],
               ['Hacer Respaldo Electronico de Documentos al Servidor', [None], [None]],],
    'Logic': [['', [None], [None]], ],
    'Complete': [['Carro a Estacion Final', [None], [None]],['Fin de pruebas', [None], [None]], ],
    'Stopped': ['Detenido'],
    'Reassigned': ['Reasignado'],}
percentage_of_time = {
    '2000':{'Beginning':0.23,
                         'Program':0.15,
                         'Logic':0.45,
                         'Ending':0.17},
    '4000':{'Beginning':0.28,
                         'Program':0.24,
                         'Logic':0.43,
                         'Ending':0.05},
    'ELEM':{'Beginning':0.18,
                         'Program':0.55,
                         'Logic':0,
                         'Ending':0.27}}
times_per_category = {
    '2000':
        {1:4*60,
         2:4.5*60,
         3:5*60,
         4:6*60,
         5:7*60,
         6:8*60,},
    '4000':
        {1: 7*60,
         2: 8*60,
         3: 10*60,
         4: 13*60,
         5: 15*60,
         6: 16*60, },
    'ELEM':
        {1:3*60,},
    'ELEMT':
        {1:3*60,},
}
stop_reasons = [('Job reassignment', 'Job reassignment'),
                ('Shift ended','Shift ended'),
                ('Error Funcional', 'Error Funcional'),
                ('Tarjetas T', 'Tarjetas T'),
                ('Material Faltante', 'Custom Software Faltante'),
                ('Junta de supervisor', 'Junta de supervisor'),
                ('Tecnico no asignado', 'Tecnico no asignado'),
                ('Personal', 'Personal'),
                ('Ingenieria', 'Ingenieria'),
                ('Falla en equipo de computo', 'Falla en equipo de computo'),
                ('Entrenamiento', 'Entrenamiento')]#TODO is this list still needed?
stations_dict = [('1', 'S1'),
                 ('2', 'S2'),
                 ('3', 'S3'),
                 ('4', 'S4'),
                 ('5', 'S5'),
                 ('6', 'S6'),
                 ('7', 'S7'),
                 ('8', 'S8'),
                 ('9', 'S9'),
                 ('10', 'S10'),
                 ('11', 'S11'),
                 ('12', 'S12'),
                 ('13', 'ELEM1'),
                 ('14', 'ELEM2')]
status_dict = [('Beginning', 'Beginning'),
               ('Program', 'Program'),
               ('Logic', 'Logic'),
               ('Ending', 'Ending'),
               ('Complete', 'Complete'),
               ('Stopped', 'Stopped'),
               ('Reassigned', 'Reassigned'),
               ('Rework', 'Rework')]
type_of_jobs = [('2000', 'M2000'),
                ('4000', 'M4000'),
                ('ELEM', 'Element-Hydro'),
                ('ELEMT', 'Element-Traction')]
features_list = [
    ('SHC', 'Serial Hall Calls'),
    ('HAPS', 'HAPS battery'),
    ('OVL', 'Overlay'),
    ('GROUP', 'Group'),
    ('mView', 'mView'),
    ('iMon', 'iMonitor'),
    ('DCC', _('Door Control in Cartop')),
    ('CPI', _('CPI Board Included')),
    ('PC', 'PC de cliente'),
    ('BCV', 'Brake Coil Voltage > 100'),
    ('MBRAKE', 'EMBRAKE Module'),
    ('EMCO', 'EMCO BOARD'),
    ('R6', 'R6 Regen Unit'),
    ('REAR', 'Rear Doors'),
    ('2STARTERS', '2+ Starters'),
    ('MANUAL', 'Manual Doors'),
    ('DUP', 'Duplex'),
    ('LOC', 'Local'),
    ('SHORTF', 'Short Floors'),
    ('CUST', 'Custom'),
    ('EDGE', 'EDGE-LS'),
    ('RAIL', 'RAIL-LS'),
    ('MOD', 'MOD Door Operator'),
    ('MRL', 'MRL'),
    ('CTL2', 'CTL2'),
    ('TSSA', 'TSSA'), ]
features = (('SHC', 'Serial Hall Calls'),
    ('HAPS', 'HAPS Battery'),
    ('DCC', _('Door Control in Cartop')),
    ('CPI', _('CPI Board Included')),
    ('OVL', 'Overlay'),
    ('GROUP', 'Group'),
    ('mView', 'mView'),
    ('iMon', 'iMonitor'),
    ('PC', 'PC de cliente'),
    ('BCV', 'Brake Coil Voltage > 100'),
    ('MBRAKE', 'EMBRAKE Module'),
    ('EMCO', 'EMCO BOARD'),
    ('R6', 'R6 Regen Unit'),
    ('REAR', 'Rear Doors'),
    ('2STARTERS', '2+ Starters'),
    ('MANUAL', 'Manual Doors'),
    ('DUP', 'Duplex'),
    ('LOC', 'Local'),
    ('SHORTF', 'Short Floors'),
    ('CUST', 'Custom'),
    ('MRL', 'MRL'),
    ('CTL2', 'CTL2'),
    ('CAN', 'Canada'),
    ('EDGE', 'EDGE-LS'),
    ('RAIL', 'RAIL-LS'),
    ('MOD', 'MOD Door Operator'),
    ('TSSA', 'TSSA(Ontario)'),
    ('None', _('None')))
stations_tupple = (('1', 'S1'),
            ('2', 'S2'),
            ('3', 'S3'),
            ('4', 'S4'),
            ('5', 'S5'),
            ('6', 'S6'),
            ('7', 'S7'),
            ('8', 'S8'),
            ('9', 'S9'),
            ('10', 'S10'),
            ('11', 'S11'),
            ('12', 'S12'),
            ('13', 'ELEM1'),
            ('14', 'ELEM2'))
label_admin = [('-', '-'),
               ('A', 'A'),
               ('B', 'B'),
               ('C', 'C'),
               ('D', 'D'),
               ('E', 'E'),
               ('F', 'F'),
               ('G', 'G'),
               ('H', 'H')]
label = (('-', '-'),
         ('A', 'A'),
         ('B', 'B'),
         ('C', 'C'),
         ('D', 'D'),
         ('E', 'E'),
         ('F', 'F'),
         ('G', 'G'),
         ('H', 'H'))
job_type_tupple = (('2000', 'M2000'),
            ('4000', 'M4000'),
            ('ELEM', 'Element-Hydro'),
            ('ELEMT', 'Element-Traction'))
stations_by_type = {
    '2000': {'0': '----',
             '1': 'S1',
             '2': 'S2',
             '3': 'S3',
             '4': 'S4',
             '5': 'S5',
             '6': 'S6'},
    '4000': {'0': '----',
             '7': 'S7',
             '8': 'S8',
             '9': 'S9',
             '10': 'S10',
             '11': 'S11',
             '12': 'S12'},
    'ELEM': {'0': '----',
             '13': 'ELEM1',
             '14': 'ELEM2'},
    'ELEMT': {'0': '----',
             '13': 'ELEM1',
             '14': 'ELEM2'}}
status_dict_tupple = (('Beginning', 'Beginning'),
                      ('Program', 'Program'),
                      ('Logic', 'Logic'),
                      ('Ending', 'Ending'),
                      ('Complete', 'Complete'),
                      ('Stopped', 'Stopped'),
                      ('Reassigned', 'Reassigned'),
                      ('Rework', 'Rework'))
headers = ['Job #',
           'PO',
           'Job Type',
           'Status',
           'Station',
           'Start Date',
           'End Date',
           'Beginning',
           'Program',
           'Logic',
           'Ending',
           'Elapsed Time on Job',
           '# of Stops',
           'Time on Stops',
           'Effective Time on Job',
           'Category',
           'Technician']
stops_headers = ['Job #',
                 'PO',
                 'Job Type',
                 'Start',
                 'Stop',
                 'Reason',
                 'Cause',
                 'Add. Cause',
                 'Description',
                 'Solution',
                 'Station',
                 'Day(s) on Stop',
                 'Time on Stop',
                 'Technician']
mureassign_headers = [
    'Reassign?',
    'Job #',
    'Prod #',
    'Tech',
    'Station',
    'Reason']
times_dict = {
    '2000': {'Beginning': 60,
             'Program': 40,
             'Logic': 110,
             'Ending': 45},
    '4000': {'Beginning': 240,
             'Program': 205,
             'Logic': 370,
             'Ending': 30},
    'ELEM': {'Beginning': 40,
             'Program': 120,
             'Logic':0,
             'Ending': 60},
    'ELEMT': {'Beginning': 80,
             'Program': 240,
             'Logic':0,
             'Ending': 120}}
times_to_add_dict = {
    '2000': {'CPI': 25, 'SHC': 10},
    '4000': {'CPI': 10, 'SHC': 20},
    'ELEM': {'HAPS': 15, },
    'ELEMT': { }}
dict_of_stages = {
    1: 'Beginning',
    2: 'Program',
    3: 'Logic',
    4: 'Ending',
    5: 'Complete'}
