# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=200)),
                ('cause', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='Issue Start Date')),
                ('end_time', models.DateTimeField(verbose_name='Issue End Date')),
            ],
            options={
                'verbose_name': 'Server Stop',
                'verbose_name_plural': 'Server Stop',
            },
        ),
    ]
