# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_issue_causes', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Server Issues Cause',
                'verbose_name_plural': 'Server Issues Causes',
            },
        ),
    ]
